### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

### ISSUE THREAD

**Issue by dpendolino** [SavageCore/atom-meld#1]
[Enter steps to reproduce below:]

1. Open file
2. Atom Meld -> Diff with File

**Atom Version**: 1.13.1
**Electron Version**: 1.4.15
**System**: "Arch Linux"
**Thrown From**: [atom-meld](https://github.com/SavageCore/atom-meld) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

```
At /home/dpendolino/.atom/packages/atom-meld/lib/atom-meld.coffee:107

TypeError: Cannot read property 'showOpenDialog' of undefined
    at Object.diff_from_tree_file (/home/dpendolino/.atom/packages/atom-meld/lib/atom-meld.coffee:107:24)
    at HTMLOListElement.commands.add.atom.commands.add.atom-meld:diff-from-tree-file (/home/dpendolino/.atom/packages/atom-meld/lib/atom-meld.coffee:64:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/lib/atom/src/atom-environment.js:1181:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:26.9.0 atom-meld:diff-from-file-file (input.hidden-input)
     -0:55.2.0 core:backspace (input.hidden-input)
     -0:21.3.0 atom-meld:diff-from-file-tab (input.hidden-input)
     -0:00.0 atom-meld:diff-from-tree-file (span.name.icon.icon-file-text.am-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "language-gfm"
    ],
    "projectHome": "/home/dpendolino/CHC/git",
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ansible-snippets, v0.2.0 (inactive)
atom-ctags, v5.0.0 (active)
atom-jade, v0.3.0 (active)
atom-material-syntax, v1.0.2 (inactive)
atom-material-ui, v1.3.9 (inactive)
atom-meld, v0.2.1 (active)
atom-vagrant-manager, v1.0.4 (inactive)
autocomplete-ansible, v0.1.11 (active)
autocomplete-ctags, v0.4.1 (active)
autocomplete-json, v5.2.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-php, v0.3.7 (active)
autocomplete-python, v1.8.28 (active)
autocomplete-xml, v0.9.4 (active)
clipboard-plus, v0.5.1 (active)
docker, v0.7.0 (inactive)
editorconfig, v2.2.0 (active)
git-control, v0.8.2 (inactive)
git-plus, v7.2.0 (active)
git-time-machine, v1.5.4 (inactive)
gitignore-snippets, v0.2.5 (inactive)
javascript-snippets, v1.2.1 (active)
language-ansible, v0.2.1 (active)
language-markdown, v0.19.1 (active)
language-powershell, v4.0.0 (active)
linter, v1.11.21 (active)
linter-ansible-linting, v1.2.2 (active)
linter-docker, v0.1.4 (active)
linter-php, v1.3.1 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-writer, v2.6.3 (inactive)
meteor-api, v2.20.0 (active)
minimap, v4.26.7 (active)
platformio-ide-terminal, v2.2.2 (active)
project-manager, v3.3.3 (active)
sync-settings, v0.8.1 (active)
tree-view-git-status, v1.3.0 (active)
vagrant, v0.1.0 (active)
vim-mode-clipboard-plus, v0.2.0 (active)
vim-mode-plus, v0.81.0 (active)
vim-mode-plus-ex-mode, v0.8.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (active)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by SavageCore** [comment]
This also applies to

atom-meld:diff-from-file-file
atom-meld:diff-from-tab-file
