### ISSUE TITLE
Uncaught TypeError: treeView.serialize is not a function

### ISSUE THREAD

**Issue by mghariani** [SavageCore/atom-meld#5]
1. select package meld from packages menu
2. select "Diff active file from open tab"

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 14.04.5
**Thrown From**: [atom-meld](https://github.com/SavageCore/atom-meld) package 0.3.3

### Stack Trace

Uncaught TypeError: treeView.serialize is not a function

```
At /home/mghariani/.atom/packages/atom-meld/lib/atom-meld.coffee:136

TypeError: treeView.serialize is not a function
    at Object.getSelectedTree (/packages/atom-meld/lib/atom-meld.coffee:136:30)
    at Object.diff_from_file_tab (/packages/atom-meld/lib/atom-meld.coffee:82:19)
    at /packages/atom-meld/lib/atom-meld.coffee:43:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1286:1)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:49.9.0 core:copy (input.hidden-input)
     -1:22.5.0 core:select-all (input.hidden-input)
     -1:21.7.0 core:copy (input.hidden-input)
     -1:17.3.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:16.1.0 core:paste (input.hidden-input)
     -1:13.3.0 core:copy (input.hidden-input)
     -1:11.4.0 core:paste (input.hidden-input)
     -1:02.5.0 settings-view:open (input.hidden-input)
     -0:58.9.0 core:confirm (input.hidden-input)
     -0:18.9.0 atom-meld:diff-from-file-tab (input.hidden-input)
```

### Non-Core Packages

```
atom-meld 0.3.3 
docker 0.7.0 
highlight-selected 0.13.1 
minimap 4.28.2 
```

**Comment by SavageCore** [comment]
Thanks for the report, I have fixes incoming for 1.17.0 issues soon.
