### ISSUE TITLE
Failed to spawn command meld. Make sure meld is installed and on your PATH

### ISSUE THREAD

**Issue by shub810** [SavageCore/atom-meld#9]
Meld is not working while differentiating between two files. 
Error : 
Uncaught (in promise) TypeError: treeViewPkg.mainModule.treeView.find is not a function
    at /home/shub810/.atom/packages/term3/index.coffee:140:39
<embedded>:71136 
spell-check:en-in Can't load en_IN: Cannot find dictionary for en_IN.
<embedded>:116467 
Uncaught Error: Failed to spawn command `meld`. Make sure `meld` is installed and on your PATH
    at BufferedProcess.handleError (/usr/share/atom/resources/app/src/buffered-process.js:388:23)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:373:22)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by SavageCore** [comment]
Can you run meld from the command line? This looks like an installation issue.

**Comment by shub810** [comment]
Yes I tried it. Same error.

**Comment by SavageCore** [comment]
I'd try to reinstall or contact meld maintainers then for your distro
